package com.example.traductorpseudocodigo.javafiles;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\076\000\002\002\004\000\002\002\005\000\002\003" +
    "\005\000\002\005\004\000\002\005\003\000\002\006\006" +
    "\000\002\006\005\000\002\006\004\000\002\006\004\000" +
    "\002\006\004\000\002\006\012\000\002\006\012\000\002" +
    "\007\003\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\010\005\000\002\010\005\000\002\010\005" +
    "\000\002\010\005\000\002\010\005\000\002\010\004\000" +
    "\002\010\005\000\002\011\005\000\002\011\005\000\002" +
    "\011\005\000\002\011\005\000\002\011\005\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\004\003" +
    "\000\002\012\004\000\002\012\003\000\002\013\005\000" +
    "\002\013\007\000\002\013\007\000\002\013\007\000\002" +
    "\013\007\000\002\013\007\000\002\013\007\000\002\013" +
    "\007\000\002\013\007\000\002\013\007\000\002\013\007" +
    "\000\002\013\007\000\002\013\007\000\002\013\007\000" +
    "\002\013\007\000\002\013\007\000\002\014\003\000\002" +
    "\014\007\000\002\015\003\000\002\015\003\000\002\015" +
    "\003\000\002\015\003\000\002\015\003\000\002\015\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\256\000\004\004\006\001\002\000\004\002\260\001" +
    "\002\000\004\043\115\001\002\000\016\006\007\007\013" +
    "\011\016\013\014\014\011\017\012\001\002\000\004\017" +
    "\112\001\002\000\020\005\111\006\007\007\013\011\016" +
    "\013\014\014\011\017\012\001\002\000\004\017\110\001" +
    "\002\000\004\036\106\001\002\000\004\041\077\001\002" +
    "\000\014\015\025\016\024\017\021\020\076\041\041\001" +
    "\002\000\020\005\ufffd\006\ufffd\007\ufffd\011\ufffd\013\ufffd" +
    "\014\ufffd\017\ufffd\001\002\000\004\041\017\001\002\000" +
    "\014\015\025\016\024\017\021\035\020\041\022\001\002" +
    "\000\014\015\025\016\024\017\021\035\020\041\022\001" +
    "\002\000\120\002\uffe3\005\uffe3\006\uffe3\007\uffe3\011\uffe3" +
    "\013\uffe3\014\uffe3\017\uffe3\021\uffe3\022\uffe3\023\uffe3\024" +
    "\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3\032\uffe3" +
    "\033\uffe3\034\uffe3\037\uffe3\040\uffe3\042\uffe3\044\uffe3\045" +
    "\uffe3\046\uffe3\047\uffe3\050\uffe3\051\uffe3\052\uffe3\053\uffe3" +
    "\054\uffe3\055\uffe3\056\uffe3\057\uffe3\060\uffe3\061\uffe3\062" +
    "\uffe3\063\uffe3\001\002\000\014\015\025\016\024\017\021" +
    "\035\020\041\022\001\002\000\010\033\056\034\060\042" +
    "\057\001\002\000\120\002\uffe4\005\uffe4\006\uffe4\007\uffe4" +
    "\011\uffe4\013\uffe4\014\uffe4\017\uffe4\021\uffe4\022\uffe4\023" +
    "\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4\030\uffe4\031\uffe4" +
    "\032\uffe4\033\uffe4\034\uffe4\037\uffe4\040\uffe4\042\uffe4\044" +
    "\uffe4\045\uffe4\046\uffe4\047\uffe4\050\uffe4\051\uffe4\052\uffe4" +
    "\053\uffe4\054\uffe4\055\uffe4\056\uffe4\057\uffe4\060\uffe4\061" +
    "\uffe4\062\uffe4\063\uffe4\001\002\000\120\002\uffe5\005\uffe5" +
    "\006\uffe5\007\uffe5\011\uffe5\013\uffe5\014\uffe5\017\uffe5\021" +
    "\uffe5\022\uffe5\023\uffe5\024\uffe5\025\uffe5\026\uffe5\027\uffe5" +
    "\030\uffe5\031\uffe5\032\uffe5\033\uffe5\034\uffe5\037\uffe5\040" +
    "\uffe5\042\uffe5\044\uffe5\045\uffe5\046\uffe5\047\uffe5\050\uffe5" +
    "\051\uffe5\052\uffe5\053\uffe5\054\uffe5\055\uffe5\056\uffe5\057" +
    "\uffe5\060\uffe5\061\uffe5\062\uffe5\063\uffe5\001\002\000\026" +
    "\021\027\022\036\023\032\024\035\025\033\026\030\027" +
    "\031\030\040\031\034\032\037\001\002\000\012\015\025" +
    "\016\024\017\021\041\041\001\002\000\012\015\025\016" +
    "\024\017\021\041\041\001\002\000\012\015\025\016\024" +
    "\017\021\041\041\001\002\000\012\015\025\016\024\017" +
    "\021\041\041\001\002\000\012\015\025\016\024\017\021" +
    "\041\041\001\002\000\012\015\025\016\024\017\021\041" +
    "\041\001\002\000\012\015\025\016\024\017\021\041\041" +
    "\001\002\000\012\015\025\016\024\017\021\041\041\001" +
    "\002\000\012\015\025\016\024\017\021\041\041\001\002" +
    "\000\012\015\025\016\024\017\021\041\041\001\002\000" +
    "\012\015\025\016\024\017\021\041\041\001\002\000\020" +
    "\021\027\022\036\023\032\024\035\033\ufff1\034\ufff1\042" +
    "\ufff1\001\002\000\014\021\027\022\036\023\032\024\035" +
    "\042\044\001\002\000\120\002\uffe6\005\uffe6\006\uffe6\007" +
    "\uffe6\011\uffe6\013\uffe6\014\uffe6\017\uffe6\021\uffe6\022\uffe6" +
    "\023\uffe6\024\uffe6\025\uffe6\026\uffe6\027\uffe6\030\uffe6\031" +
    "\uffe6\032\uffe6\033\uffe6\034\uffe6\037\uffe6\040\uffe6\042\uffe6" +
    "\044\uffe6\045\uffe6\046\uffe6\047\uffe6\050\uffe6\051\uffe6\052" +
    "\uffe6\053\uffe6\054\uffe6\055\uffe6\056\uffe6\057\uffe6\060\uffe6" +
    "\061\uffe6\062\uffe6\063\uffe6\001\002\000\020\021\027\022" +
    "\036\023\032\024\035\033\uffef\034\uffef\042\uffef\001\002" +
    "\000\120\002\uffe9\005\uffe9\006\uffe9\007\uffe9\011\uffe9\013" +
    "\uffe9\014\uffe9\017\uffe9\021\uffe9\022\uffe9\023\032\024\035" +
    "\025\uffe9\026\uffe9\027\uffe9\030\uffe9\031\uffe9\032\uffe9\033" +
    "\uffe9\034\uffe9\037\uffe9\040\uffe9\042\uffe9\044\uffe9\045\uffe9" +
    "\046\uffe9\047\uffe9\050\uffe9\051\uffe9\052\uffe9\053\uffe9\054" +
    "\uffe9\055\uffe9\056\uffe9\057\uffe9\060\uffe9\061\uffe9\062\uffe9" +
    "\063\uffe9\001\002\000\120\002\uffe7\005\uffe7\006\uffe7\007" +
    "\uffe7\011\uffe7\013\uffe7\014\uffe7\017\uffe7\021\uffe7\022\uffe7" +
    "\023\uffe7\024\uffe7\025\uffe7\026\uffe7\027\uffe7\030\uffe7\031" +
    "\uffe7\032\uffe7\033\uffe7\034\uffe7\037\uffe7\040\uffe7\042\uffe7" +
    "\044\uffe7\045\uffe7\046\uffe7\047\uffe7\050\uffe7\051\uffe7\052" +
    "\uffe7\053\uffe7\054\uffe7\055\uffe7\056\uffe7\057\uffe7\060\uffe7" +
    "\061\uffe7\062\uffe7\063\uffe7\001\002\000\020\021\027\022" +
    "\036\023\032\024\035\033\ufff0\034\ufff0\042\ufff0\001\002" +
    "\000\020\021\027\022\036\023\032\024\035\033\ufff4\034" +
    "\ufff4\042\ufff4\001\002\000\120\002\uffe8\005\uffe8\006\uffe8" +
    "\007\uffe8\011\uffe8\013\uffe8\014\uffe8\017\uffe8\021\uffe8\022" +
    "\uffe8\023\uffe8\024\uffe8\025\uffe8\026\uffe8\027\uffe8\030\uffe8" +
    "\031\uffe8\032\uffe8\033\uffe8\034\uffe8\037\uffe8\040\uffe8\042" +
    "\uffe8\044\uffe8\045\uffe8\046\uffe8\047\uffe8\050\uffe8\051\uffe8" +
    "\052\uffe8\053\uffe8\054\uffe8\055\uffe8\056\uffe8\057\uffe8\060" +
    "\uffe8\061\uffe8\062\uffe8\063\uffe8\001\002\000\020\021\027" +
    "\022\036\023\032\024\035\033\ufff2\034\ufff2\042\ufff2\001" +
    "\002\000\020\021\027\022\036\023\032\024\035\033\ufff3" +
    "\034\ufff3\042\ufff3\001\002\000\120\002\uffea\005\uffea\006" +
    "\uffea\007\uffea\011\uffea\013\uffea\014\uffea\017\uffea\021\uffea" +
    "\022\uffea\023\032\024\035\025\uffea\026\uffea\027\uffea\030" +
    "\uffea\031\uffea\032\uffea\033\uffea\034\uffea\037\uffea\040\uffea" +
    "\042\uffea\044\uffea\045\uffea\046\uffea\047\uffea\050\uffea\051" +
    "\uffea\052\uffea\053\uffea\054\uffea\055\uffea\056\uffea\057\uffea" +
    "\060\uffea\061\uffea\062\uffea\063\uffea\001\002\000\014\015" +
    "\025\016\024\017\021\035\020\041\022\001\002\000\004" +
    "\012\062\001\002\000\014\015\025\016\024\017\021\035" +
    "\020\041\022\001\002\000\010\033\056\034\uffed\042\uffed" +
    "\001\002\000\016\006\007\007\013\011\016\013\014\014" +
    "\011\017\012\001\002\000\004\005\066\001\002\000\020" +
    "\005\ufff5\006\007\007\013\011\016\013\014\014\011\017" +
    "\012\001\002\000\020\005\ufffe\006\ufffe\007\ufffe\011\ufffe" +
    "\013\ufffe\014\ufffe\017\ufffe\001\002\000\004\011\067\001" +
    "\002\000\020\005\ufff6\006\ufff6\007\ufff6\011\ufff6\013\ufff6" +
    "\014\ufff6\017\ufff6\001\002\000\010\033\uffee\034\uffee\042" +
    "\uffee\001\002\000\010\033\056\034\060\042\073\001\002" +
    "\000\030\021\027\022\036\023\032\024\035\025\033\026" +
    "\030\027\031\030\040\031\034\032\037\042\044\001\002" +
    "\000\010\033\uffeb\034\uffeb\042\uffeb\001\002\000\010\033" +
    "\uffec\034\uffec\042\uffec\001\002\000\030\005\ufffa\006\ufffa" +
    "\007\ufffa\011\ufffa\013\ufffa\014\ufffa\017\ufffa\021\027\022" +
    "\036\023\032\024\035\001\002\000\020\005\ufff9\006\ufff9" +
    "\007\ufff9\011\ufff9\013\ufff9\014\ufff9\017\ufff9\001\002\000" +
    "\014\015\025\016\024\017\021\035\020\041\022\001\002" +
    "\000\010\033\056\034\060\042\101\001\002\000\004\010" +
    "\102\001\002\000\016\006\007\007\013\011\016\013\014" +
    "\014\011\017\012\001\002\000\004\005\104\001\002\000" +
    "\004\007\105\001\002\000\020\005\ufff7\006\ufff7\007\ufff7" +
    "\011\ufff7\013\ufff7\014\ufff7\017\ufff7\001\002\000\012\015" +
    "\025\016\024\017\021\041\041\001\002\000\030\005\ufffb" +
    "\006\ufffb\007\ufffb\011\ufffb\013\ufffb\014\ufffb\017\ufffb\021" +
    "\027\022\036\023\032\024\035\001\002\000\020\005\ufff8" +
    "\006\ufff8\007\ufff8\011\ufff8\013\ufff8\014\ufff8\017\ufff8\001" +
    "\002\000\004\043\uffff\001\002\000\004\036\113\001\002" +
    "\000\012\015\025\016\024\017\021\041\041\001\002\000" +
    "\030\005\ufffc\006\ufffc\007\ufffc\011\ufffc\013\ufffc\014\ufffc" +
    "\017\ufffc\021\027\022\036\023\032\024\035\001\002\000" +
    "\042\044\136\045\131\046\135\047\127\050\122\051\116" +
    "\052\134\053\126\054\133\055\132\056\124\057\121\060" +
    "\125\061\140\062\123\063\130\001\002\000\004\036\254" +
    "\001\002\000\044\002\uffe0\044\uffe0\045\uffe0\046\uffe0\047" +
    "\uffe0\050\uffe0\051\uffe0\052\uffe0\053\uffe0\054\uffe0\055\uffe0" +
    "\056\uffe0\057\uffe0\060\uffe0\061\uffe0\062\uffe0\063\uffe0\001" +
    "\002\000\044\002\uffe2\044\136\045\131\046\135\047\127" +
    "\050\122\051\116\052\134\053\126\054\133\055\132\056" +
    "\124\057\121\060\125\061\140\062\123\063\130\001\002" +
    "\000\004\036\247\001\002\000\004\036\243\001\002\000" +
    "\004\036\237\001\002\000\004\036\233\001\002\000\004" +
    "\036\227\001\002\000\004\036\223\001\002\000\004\036" +
    "\217\001\002\000\004\036\213\001\002\000\004\036\207" +
    "\001\002\000\004\036\177\001\002\000\004\036\173\001" +
    "\002\000\004\036\167\001\002\000\004\036\155\001\002" +
    "\000\004\036\153\001\002\000\004\002\000\001\002\000" +
    "\004\036\141\001\002\000\016\064\150\065\146\066\145" +
    "\067\142\070\147\071\144\001\002\000\004\037\uffca\001" +
    "\002\000\004\037\151\001\002\000\004\037\uffc8\001\002" +
    "\000\004\037\uffcb\001\002\000\004\037\uffcc\001\002\000" +
    "\004\037\uffc9\001\002\000\004\037\uffcd\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\054\002" +
    "\uffd2\021\027\022\036\023\032\024\035\044\uffd2\045\uffd2" +
    "\046\uffd2\047\uffd2\050\uffd2\051\uffd2\052\uffd2\053\uffd2\054" +
    "\uffd2\055\uffd2\056\uffd2\057\uffd2\060\uffd2\061\uffd2\062\uffd2" +
    "\063\uffd2\001\002\000\012\015\025\016\024\017\021\041" +
    "\041\001\002\000\054\002\uffdf\021\027\022\036\023\032" +
    "\024\035\044\uffdf\045\uffdf\046\uffdf\047\uffdf\050\uffdf\051" +
    "\uffdf\052\uffdf\053\uffdf\054\uffdf\055\uffdf\056\uffdf\057\uffdf" +
    "\060\uffdf\061\uffdf\062\uffdf\063\uffdf\001\002\000\014\015" +
    "\025\016\024\017\021\041\041\076\157\001\002\000\004" +
    "\037\165\001\002\000\004\037\uffcf\001\002\000\014\021" +
    "\027\022\036\023\032\024\035\040\161\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\014\021" +
    "\027\022\036\023\032\024\035\040\163\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\014\021" +
    "\027\022\036\023\032\024\035\037\uffce\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\054\002" +
    "\uffdd\021\027\022\036\023\032\024\035\044\uffdd\045\uffdd" +
    "\046\uffdd\047\uffdd\050\uffdd\051\uffdd\052\uffdd\053\uffdd\054" +
    "\uffdd\055\uffdd\056\uffdd\057\uffdd\060\uffdd\061\uffdd\062\uffdd" +
    "\063\uffdd\001\002\000\014\015\025\016\024\017\021\041" +
    "\041\076\157\001\002\000\004\037\171\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\054\002" +
    "\uffd9\021\027\022\036\023\032\024\035\044\uffd9\045\uffd9" +
    "\046\uffd9\047\uffd9\050\uffd9\051\uffd9\052\uffd9\053\uffd9\054" +
    "\uffd9\055\uffd9\056\uffd9\057\uffd9\060\uffd9\061\uffd9\062\uffd9" +
    "\063\uffd9\001\002\000\016\064\150\065\146\066\145\067" +
    "\142\070\147\071\144\001\002\000\004\037\175\001\002" +
    "\000\012\015\025\016\024\017\021\041\041\001\002\000" +
    "\054\002\uffd7\021\027\022\036\023\032\024\035\044\uffd7" +
    "\045\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7\052\uffd7\053" +
    "\uffd7\054\uffd7\055\uffd7\056\uffd7\057\uffd7\060\uffd7\061\uffd7" +
    "\062\uffd7\063\uffd7\001\002\000\012\072\201\073\204\074" +
    "\200\075\203\001\002\000\004\037\uffc5\001\002\000\004" +
    "\037\uffc7\001\002\000\004\037\205\001\002\000\004\037" +
    "\uffc4\001\002\000\004\037\uffc6\001\002\000\012\015\025" +
    "\016\024\017\021\041\041\001\002\000\054\002\uffd6\021" +
    "\027\022\036\023\032\024\035\044\uffd6\045\uffd6\046\uffd6" +
    "\047\uffd6\050\uffd6\051\uffd6\052\uffd6\053\uffd6\054\uffd6\055" +
    "\uffd6\056\uffd6\057\uffd6\060\uffd6\061\uffd6\062\uffd6\063\uffd6" +
    "\001\002\000\014\015\025\016\024\017\021\041\041\076" +
    "\157\001\002\000\004\037\211\001\002\000\012\015\025" +
    "\016\024\017\021\041\041\001\002\000\054\002\uffde\021" +
    "\027\022\036\023\032\024\035\044\uffde\045\uffde\046\uffde" +
    "\047\uffde\050\uffde\051\uffde\052\uffde\053\uffde\054\uffde\055" +
    "\uffde\056\uffde\057\uffde\060\uffde\061\uffde\062\uffde\063\uffde" +
    "\001\002\000\012\015\025\016\024\017\021\041\041\001" +
    "\002\000\014\021\027\022\036\023\032\024\035\037\215" +
    "\001\002\000\012\015\025\016\024\017\021\041\041\001" +
    "\002\000\054\002\uffd0\021\027\022\036\023\032\024\035" +
    "\044\uffd0\045\uffd0\046\uffd0\047\uffd0\050\uffd0\051\uffd0\052" +
    "\uffd0\053\uffd0\054\uffd0\055\uffd0\056\uffd0\057\uffd0\060\uffd0" +
    "\061\uffd0\062\uffd0\063\uffd0\001\002\000\016\064\150\065" +
    "\146\066\145\067\142\070\147\071\144\001\002\000\004" +
    "\037\221\001\002\000\012\015\025\016\024\017\021\041" +
    "\041\001\002\000\054\002\uffdc\021\027\022\036\023\032" +
    "\024\035\044\uffdc\045\uffdc\046\uffdc\047\uffdc\050\uffdc\051" +
    "\uffdc\052\uffdc\053\uffdc\054\uffdc\055\uffdc\056\uffdc\057\uffdc" +
    "\060\uffdc\061\uffdc\062\uffdc\063\uffdc\001\002\000\014\015" +
    "\025\016\024\017\021\041\041\076\157\001\002\000\004" +
    "\037\225\001\002\000\012\015\025\016\024\017\021\041" +
    "\041\001\002\000\054\002\uffd8\021\027\022\036\023\032" +
    "\024\035\044\uffd8\045\uffd8\046\uffd8\047\uffd8\050\uffd8\051" +
    "\uffd8\052\uffd8\053\uffd8\054\uffd8\055\uffd8\056\uffd8\057\uffd8" +
    "\060\uffd8\061\uffd8\062\uffd8\063\uffd8\001\002\000\014\015" +
    "\025\016\024\017\021\041\041\076\157\001\002\000\004" +
    "\037\231\001\002\000\012\015\025\016\024\017\021\041" +
    "\041\001\002\000\054\002\uffd3\021\027\022\036\023\032" +
    "\024\035\044\uffd3\045\uffd3\046\uffd3\047\uffd3\050\uffd3\051" +
    "\uffd3\052\uffd3\053\uffd3\054\uffd3\055\uffd3\056\uffd3\057\uffd3" +
    "\060\uffd3\061\uffd3\062\uffd3\063\uffd3\001\002\000\012\015" +
    "\025\016\024\017\021\041\041\001\002\000\014\021\027" +
    "\022\036\023\032\024\035\037\235\001\002\000\012\015" +
    "\025\016\024\017\021\041\041\001\002\000\054\002\uffd5" +
    "\021\027\022\036\023\032\024\035\044\uffd5\045\uffd5\046" +
    "\uffd5\047\uffd5\050\uffd5\051\uffd5\052\uffd5\053\uffd5\054\uffd5" +
    "\055\uffd5\056\uffd5\057\uffd5\060\uffd5\061\uffd5\062\uffd5\063" +
    "\uffd5\001\002\000\012\072\201\073\204\074\200\075\203" +
    "\001\002\000\004\037\241\001\002\000\012\015\025\016" +
    "\024\017\021\041\041\001\002\000\054\002\uffd1\021\027" +
    "\022\036\023\032\024\035\044\uffd1\045\uffd1\046\uffd1\047" +
    "\uffd1\050\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1\055\uffd1" +
    "\056\uffd1\057\uffd1\060\uffd1\061\uffd1\062\uffd1\063\uffd1\001" +
    "\002\000\012\072\201\073\204\074\200\075\203\001\002" +
    "\000\004\037\245\001\002\000\012\015\025\016\024\017" +
    "\021\041\041\001\002\000\054\002\uffdb\021\027\022\036" +
    "\023\032\024\035\044\uffdb\045\uffdb\046\uffdb\047\uffdb\050" +
    "\uffdb\051\uffdb\052\uffdb\053\uffdb\054\uffdb\055\uffdb\056\uffdb" +
    "\057\uffdb\060\uffdb\061\uffdb\062\uffdb\063\uffdb\001\002\000" +
    "\014\015\025\016\024\017\021\041\041\076\157\001\002" +
    "\000\004\037\251\001\002\000\012\015\025\016\024\017" +
    "\021\041\041\001\002\000\054\002\uffd4\021\027\022\036" +
    "\023\032\024\035\044\uffd4\045\uffd4\046\uffd4\047\uffd4\050" +
    "\uffd4\051\uffd4\052\uffd4\053\uffd4\054\uffd4\055\uffd4\056\uffd4" +
    "\057\uffd4\060\uffd4\061\uffd4\062\uffd4\063\uffd4\001\002\000" +
    "\044\002\uffe1\044\uffe1\045\uffe1\046\uffe1\047\uffe1\050\uffe1" +
    "\051\uffe1\052\uffe1\053\uffe1\054\uffe1\055\uffe1\056\uffe1\057" +
    "\uffe1\060\uffe1\061\uffe1\062\uffe1\063\uffe1\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\014\021" +
    "\027\022\036\023\032\024\035\037\256\001\002\000\012" +
    "\015\025\016\024\017\021\041\041\001\002\000\054\002" +
    "\uffda\021\027\022\036\023\032\024\035\044\uffda\045\uffda" +
    "\046\uffda\047\uffda\050\uffda\051\uffda\052\uffda\053\uffda\054" +
    "\uffda\055\uffda\056\uffda\057\uffda\060\uffda\061\uffda\062\uffda" +
    "\063\uffda\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\256\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\005\007\006\014\001\001" +
    "\000\002\001\001\000\004\006\064\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\074" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\010" +
    "\022\011\025\001\001\000\006\010\073\011\025\001\001" +
    "\000\002\001\001\000\006\010\070\011\071\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\054\001\001\000\004\011\053\001" +
    "\001\000\004\011\052\001\001\000\004\011\051\001\001" +
    "\000\004\011\050\001\001\000\004\011\047\001\001\000" +
    "\004\011\046\001\001\000\004\011\045\001\001\000\004" +
    "\011\044\001\001\000\004\011\041\001\001\000\004\011" +
    "\042\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\010\067\011\025\001\001\000\002\001\001\000\006" +
    "\010\060\011\025\001\001\000\002\001\001\000\010\005" +
    "\063\006\014\007\062\001\001\000\002\001\001\000\004" +
    "\006\064\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\010\077\011\025\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\005\063\006" +
    "\014\007\102\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\106\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\113\001\001\000\002\001\001\000\010\004" +
    "\136\012\117\013\116\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\252\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\142\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\151\001\001\000\002\001\001\000" +
    "\004\011\153\001\001\000\002\001\001\000\006\011\157" +
    "\014\155\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\161\001\001\000\002\001\001" +
    "\000\004\011\163\001\001\000\002\001\001\000\004\011" +
    "\165\001\001\000\002\001\001\000\006\011\157\014\167" +
    "\001\001\000\002\001\001\000\004\011\171\001\001\000" +
    "\002\001\001\000\004\015\173\001\001\000\002\001\001" +
    "\000\004\011\175\001\001\000\002\001\001\000\004\016" +
    "\201\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\205\001\001\000\002\001\001\000\006\011\157\014\207" +
    "\001\001\000\002\001\001\000\004\011\211\001\001\000" +
    "\002\001\001\000\004\011\213\001\001\000\002\001\001" +
    "\000\004\011\215\001\001\000\002\001\001\000\004\015" +
    "\217\001\001\000\002\001\001\000\004\011\221\001\001" +
    "\000\002\001\001\000\006\011\157\014\223\001\001\000" +
    "\002\001\001\000\004\011\225\001\001\000\002\001\001" +
    "\000\006\011\157\014\227\001\001\000\002\001\001\000" +
    "\004\011\231\001\001\000\002\001\001\000\004\011\233" +
    "\001\001\000\002\001\001\000\004\011\235\001\001\000" +
    "\002\001\001\000\004\016\237\001\001\000\002\001\001" +
    "\000\004\011\241\001\001\000\002\001\001\000\004\016" +
    "\243\001\001\000\002\001\001\000\004\011\245\001\001" +
    "\000\002\001\001\000\006\011\157\014\247\001\001\000" +
    "\002\001\001\000\004\011\251\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\254\001\001\000\002\001" +
    "\001\000\004\011\256\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public Symbol do_action(
    int                        act_num,
    lr_parser parser,
    Stack            stack,
    int                        top)
    throws Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    Lexer lex;
    private List<String> syntaxErrors;

    public Parser(Lexer lex){
        super(lex);
        this.lex = lex;
        syntaxErrors = new ArrayList<>();
    }

    public List<String> getSyntaxErrors(){
        return this.syntaxErrors;
    }

    public void syntax_error(Symbol cur_token){
        syntaxErrors.add(
            "Error sintactico: " + cur_token.value +
            " linea " + cur_token.left +
            " columna " + cur_token.right
        );
    }

    public void unrecovered_syntax_error(Symbol cur_token){
        syntaxErrors.add("Error que no se puede recuperar");
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    lr_parser CUP$Parser$parser,
    Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
      /* Symbol object for return from actions */
      Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Programa start_val = (Programa)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= seccion_algoritmo SEPARADOR seccion_configuracion 
            {
              Programa RESULT =null;
		int algleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int algright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List alg = (List)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int confleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int confright = ((Symbol)CUP$Parser$stack.peek()).right;
		List conf = (List)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Programa(alg, conf); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // seccion_algoritmo ::= INICIO instrucciones FIN 
            {
              List RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List lista = (List)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_algoritmo",1, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instrucciones ::= instrucciones instruccion 
            {
              List RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List lista = (List)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int instleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((Symbol)CUP$Parser$stack.peek()).right;
		Instruccion inst = (Instruccion)((Symbol) CUP$Parser$stack.peek()).value;
		
            lista.add(inst);
            RESULT = lista;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones",3, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instrucciones ::= instruccion 
            {
              List RESULT =null;
		int instleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((Symbol)CUP$Parser$stack.peek()).right;
		Instruccion inst = (Instruccion)((Symbol) CUP$Parser$stack.peek()).value;
		
            List nueva = new LinkedList();
            nueva.add(inst);
            RESULT = nueva;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones",3, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= VAR IDENTIFICADOR ASIGNACION expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int expleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((Symbol)CUP$Parser$stack.peek()).right;
		String exp = (String)((Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT = new Instruccion(
                TipoInstruccion.ASIGNACION,
                "VAR " + id,
                exp
            );
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= IDENTIFICADOR ASIGNACION expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object id = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int expleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((Symbol)CUP$Parser$stack.peek()).right;
		String exp = (String)((Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT = new Instruccion(
                TipoInstruccion.ASIGNACION,
                id.toString(),
                exp
            );
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= MOSTRAR expresion 
            {
              Instruccion RESULT =null;
		int expleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((Symbol)CUP$Parser$stack.peek()).right;
		String exp = (String)((Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT = new Instruccion(
                TipoInstruccion.MOSTRAR,
                exp,
                null
            );
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= MOSTRAR CADENA 
            {
              Instruccion RESULT =null;
		int cadleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cadright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object cad = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT = new Instruccion(
                TipoInstruccion.MOSTRAR,
                cad.toString(),
                null
            );
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= LEER IDENTIFICADOR 
            {
              Instruccion RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		
            RESULT = new Instruccion(
                TipoInstruccion.LEER,
                id.toString(),
                null
            );
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= SI PA condicion PC ENTONCES bloque FIN SI 
            {
              Instruccion RESULT =null;
		int condleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int condright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String cond = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int blleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int blright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List bl = (List)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
            Instruccion inst =
                new Instruccion(TipoInstruccion.SI, cond, null);
            inst.setBloque(bl);
            RESULT = inst;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= MIENTRAS PA condicion PC HACER bloque FIN MIENTRAS 
            {
              Instruccion RESULT =null;
		int condleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int condright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String cond = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int blleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int blright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List bl = (List)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
            Instruccion inst =
                new Instruccion(TipoInstruccion.MIENTRAS, cond, null);
            inst.setBloque(bl);
            RESULT = inst;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",4, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bloque ::= instrucciones 
            {
              List RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int listaright = ((Symbol)CUP$Parser$stack.peek()).right;
		List lista = (List)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",5, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // condicion ::= expresion MAYOR expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " > " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // condicion ::= expresion MENOR expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " < " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // condicion ::= expresion MAYOR_IGUAL expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " >= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // condicion ::= expresion MENOR_IGUAL expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " <= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // condicion ::= expresion IGUAL expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " == " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // condicion ::= expresion DIFERENTE expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " != " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // condicion ::= condicion AND condicion 
            {
              String RESULT =null;
		int c1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String c2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " && " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicion ::= condicion OR condicion 
            {
              String RESULT =null;
		int c1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String c1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String c2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " || " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicion ::= NOT condicion 
            {
              String RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		String c = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = "!" + c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // condicion ::= PA condicion PC 
            {
              String RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String c = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "(" + c + ")"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",6, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= expresion SUMA expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " + " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= expresion RESTA expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " - " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= expresion MULTIPLICACION expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " * " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= expresion DIVISION expresion 
            {
              String RESULT =null;
		int e1left = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String e1 = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((Symbol)CUP$Parser$stack.peek()).right;
		String e2 = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " / " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= PA expresion PC 
            {
              String RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String e = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = "(" + e + ")"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= ENTERO 
            {
              String RESULT =null;
		int numleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int numright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object num = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = num.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= DECIMAL 
            {
              String RESULT =null;
		int decleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int decright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object dec = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = dec.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= IDENTIFICADOR 
            {
              String RESULT =null;
		int idleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object id = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = id.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // seccion_configuracion ::= config_instrucciones 
            {
              List RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int listaright = ((Symbol)CUP$Parser$stack.peek()).right;
		List lista = (List)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = lista; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_configuracion",2, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // config_instrucciones ::= config_instrucciones config_instruccion 
            {
              List RESULT =null;
		int listaleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List lista = (List)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int confleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int confright = ((Symbol)CUP$Parser$stack.peek()).right;
		Configuracion conf = (Configuracion)((Symbol) CUP$Parser$stack.peek()).value;
		
            lista.add(conf);
            RESULT = lista;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instrucciones",8, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // config_instrucciones ::= config_instruccion 
            {
              List RESULT =null;
		int confleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int confright = ((Symbol)CUP$Parser$stack.peek()).right;
		Configuracion conf = (Configuracion)((Symbol) CUP$Parser$stack.peek()).value;
		
            List nueva = new LinkedList();
            nueva.add(conf);
            RESULT = nueva;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instrucciones",8, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // config_instruccion ::= DEFAULT_TOKEN ASIGNACION expresion 
            {
              Configuracion RESULT =null;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("DEFAULT", null, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // config_instruccion ::= COLOR_TEXTO_SI ASIGNACION color TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("COLOR_TEXTO_SI", c, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // config_instruccion ::= COLOR_SI ASIGNACION color TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("COLOR_SI", c, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // config_instruccion ::= FIGURA_SI ASIGNACION figura TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int fleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object f = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("FIGURA_SI", f, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // config_instruccion ::= LETRA_SI ASIGNACION tipo_letra TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int lleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object l = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("LETRA_SI", l, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // config_instruccion ::= LETRA_SIZE_SI ASIGNACION expresion TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int valleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int valright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String val = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("LETRA_SIZE_SI", val, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // config_instruccion ::= COLOR_TEXTO_MIENTRAS ASIGNACION color TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("COLOR_TEXTO_MIENTRAS", c, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // config_instruccion ::= COLOR_MIENTRAS ASIGNACION color TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("COLOR_MIENTRAS", c, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // config_instruccion ::= FIGURA_MIENTRAS ASIGNACION figura TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int fleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object f = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("FIGURA_MIENTRAS", f, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // config_instruccion ::= LETRA_MIENTRAS ASIGNACION tipo_letra TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int lleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object l = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("LETRA_MIENTRAS", l, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // config_instruccion ::= LETRA_SIZE_MIENTRAS ASIGNACION expresion TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int valleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int valright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String val = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("LETRA_SIZE_MIENTRAS", val, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // config_instruccion ::= COLOR_TEXTO_BLOQUE ASIGNACION color TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("COLOR_TEXTO_BLOQUE", c, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // config_instruccion ::= COLOR_BLOQUE ASIGNACION color TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("COLOR_BLOQUE", c, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // config_instruccion ::= FIGURA_BLOQUE ASIGNACION figura TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int fleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int fright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object f = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("FIGURA_BLOQUE", f, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // config_instruccion ::= LETRA_BLOQUE ASIGNACION tipo_letra TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int lleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object l = (Object)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("LETRA_BLOQUE", l, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // config_instruccion ::= LETRA_SIZE_BLOQUE ASIGNACION expresion TUBERIA expresion 
            {
              Configuracion RESULT =null;
		int valleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int valright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String val = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int indleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int indright = ((Symbol)CUP$Parser$stack.peek()).right;
		String ind = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Configuracion("LETRA_SIZE_BLOQUE", val, ind); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_instruccion",9, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // color ::= COLOR_HEX 
            {
              Object RESULT =null;
		int hexleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int hexright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object hex = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = hex.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",10, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // color ::= expresion COMA expresion COMA expresion 
            {
              Object RESULT =null;
		int rleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int rright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String r = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int gleft = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int gright = ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String g = (String)((Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((Symbol)CUP$Parser$stack.peek()).right;
		String b = (String)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = r + "," + g + "," + b; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("color",10, ((Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // figura ::= ELIPSE 
            {
              Object RESULT =null;
		int eleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // figura ::= CIRCULO 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // figura ::= PARALELOGRAMO 
            {
              Object RESULT =null;
		int pleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object p = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = p.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // figura ::= RECTANGULO 
            {
              Object RESULT =null;
		int rleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object r = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = r.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // figura ::= ROMBO 
            {
              Object RESULT =null;
		int roleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int roright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object ro = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = ro.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // figura ::= RECTANGULO_REDONDEADO 
            {
              Object RESULT =null;
		int rrleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int rrright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object rr = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = rr.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("figura",11, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // tipo_letra ::= ARIAL 
            {
              Object RESULT =null;
		int aleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object a = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_letra",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // tipo_letra ::= TIMES_NEW_ROMAN 
            {
              Object RESULT =null;
		int tleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object t = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_letra",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // tipo_letra ::= COMIC_SANS 
            {
              Object RESULT =null;
		int cleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_letra",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // tipo_letra ::= VERDANA 
            {
              Object RESULT =null;
		int vleft = ((Symbol)CUP$Parser$stack.peek()).left;
		int vright = ((Symbol)CUP$Parser$stack.peek()).right;
		Object v = (Object)((Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = v.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo_letra",12, ((Symbol)CUP$Parser$stack.peek()), ((Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    lr_parser CUP$Parser$parser,
    Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
