package com.example.traductorpseudocodigo.javafiles;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR_TEXTO_BLOQUE = 45;
  public static final int LETRA_SIZE_MIENTRAS = 44;
  public static final int ENTERO = 11;
  public static final int SI = 5;
  public static final int MOSTRAR = 9;
  public static final int FIGURA_BLOQUE = 47;
  public static final int DIFERENTE = 24;
  public static final int RESTA = 16;
  public static final int PC = 32;
  public static final int LETRA_MIENTRAS = 43;
  public static final int ENTONCES = 6;
  public static final int PA = 31;
  public static final int RECTANGULO_REDONDEADO = 55;
  public static final int SEPARADOR = 33;
  public static final int FIN = 3;
  public static final int IDENTIFICADOR = 13;
  public static final int NOT = 27;
  public static final int AND = 25;
  public static final int IGUAL = 23;
  public static final int TUBERIA = 29;
  public static final int OR = 26;
  public static final int MIENTRAS = 7;
  public static final int LETRA_SIZE_BLOQUE = 49;
  public static final int ARIAL = 56;
  public static final int CIRCULO = 51;
  public static final int SUMA = 15;
  public static final int COLOR_HEX = 60;
  public static final int EOF = 0;
  public static final int DECIMAL = 12;
  public static final int error = 1;
  public static final int COLOR_BLOQUE = 46;
  public static final int COMA = 30;
  public static final int COMIC_SANS = 58;
  public static final int CADENA = 14;
  public static final int COLOR_MIENTRAS = 41;
  public static final int MENOR = 20;
  public static final int COLOR_TEXTO_MIENTRAS = 40;
  public static final int VERDANA = 59;
  public static final int LETRA_BLOQUE = 48;
  public static final int TIMES_NEW_ROMAN = 57;
  public static final int ASIGNACION = 28;
  public static final int MAYOR = 19;
  public static final int ELIPSE = 50;
  public static final int ROMBO = 54;
  public static final int DEFAULT_TOKEN = 34;
  public static final int RECTANGULO = 53;
  public static final int FIGURA_MIENTRAS = 42;
  public static final int MAYOR_IGUAL = 21;
  public static final int LEER = 10;
  public static final int HACER = 8;
  public static final int LETRA_SI = 38;
  public static final int COLOR_SI = 36;
  public static final int PARALELOGRAMO = 52;
  public static final int INICIO = 2;
  public static final int MENOR_IGUAL = 22;
  public static final int DIVISION = 18;
  public static final int COLOR_TEXTO_SI = 35;
  public static final int FIGURA_SI = 37;
  public static final int VAR = 4;
  public static final int MULTIPLICACION = 17;
  public static final int LETRA_SIZE_SI = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "MIENTRAS",
  "HACER",
  "MOSTRAR",
  "LEER",
  "ENTERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "CADENA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "AND",
  "OR",
  "NOT",
  "ASIGNACION",
  "TUBERIA",
  "COMA",
  "PA",
  "PC",
  "SEPARADOR",
  "DEFAULT_TOKEN",
  "COLOR_TEXTO_SI",
  "COLOR_SI",
  "FIGURA_SI",
  "LETRA_SI",
  "LETRA_SIZE_SI",
  "COLOR_TEXTO_MIENTRAS",
  "COLOR_MIENTRAS",
  "FIGURA_MIENTRAS",
  "LETRA_MIENTRAS",
  "LETRA_SIZE_MIENTRAS",
  "COLOR_TEXTO_BLOQUE",
  "COLOR_BLOQUE",
  "FIGURA_BLOQUE",
  "LETRA_BLOQUE",
  "LETRA_SIZE_BLOQUE",
  "ELIPSE",
  "CIRCULO",
  "PARALELOGRAMO",
  "RECTANGULO",
  "ROMBO",
  "RECTANGULO_REDONDEADO",
  "ARIAL",
  "TIMES_NEW_ROMAN",
  "COMIC_SANS",
  "VERDANA",
  "COLOR_HEX"
  };
}

